### ISSUE TITLE
Keras support

### ISSUE THREAD

**Issue by virajprabhu** [Cloud-CV/IDE#15]
We want to support [Keras](https://keras.io/) as an additional backend. 

Export: Since our intermediate backend representation is prototxt, we can use [this](https://github.com/MarcBS/keras/blob/master/keras/caffe/README.md) to export.

Import: Keras exposes a `model.to_json()` function, we will have to write logic to parse the json to prototxt.

**Comment by souravsingh** [comment]
I am interested in working on the issue. How do I start?

**Comment by virajprabhu** [comment]
Great! I'd recommend you set up the code locally if you haven't already (follow instructions in the README) and try out a few import/export workflows. The `caffe_app/views` directory contains the relevant code for caffe support. We will need a similar implementation for Keras (refer to my comment above). Once you've done that, let's have a discussion about the details of the implementation.

**Comment by souravsingh** [comment]
@virajprabhu I have finished setting up the code for the project. For adding support for Keras, it would be similar to how it is done for tensorflow, correct?

**Comment by virajprabhu** [comment]
@souravsingh Great! Yes, the approach will be similar. Do you have a fair understanding of the TensorFlow logic?

**Comment by souravsingh** [comment]
@virajprabhu I have a fair understanding of Tensorflow logic. Should I go ahead and make a WIP Pull Request to incorporate Keras Support?

**Comment by virajprabhu** [comment]
Great @souravsingh! Before you do that, we should iterate a bit over the implementation. Since this is a major feature, I'd like to make sure we are on the same page so you don't end up having to reimplement anything. Could you please summarize your proposed implementation [here](https://docs.google.com/document/d/1qdIR7S7Br9uUDUutri7xp4C2HNaduWGTuWDgpoVgMJE/edit?usp=sharing)?

**Comment by virajprabhu** [comment]
@souravsingh PR #22 (under review) was just submitted for this. Is there any other issue you'd like to work on? #17 is another major feature that we're very interested in. Let me know if there is, and I could assign it to you.

**Comment by virajprabhu** [comment]
Closing this. #22 was merged to [keras-support](https://github.com/Cloud-CV/IDE/tree/keras-support) (Still in progress).
