### ISSUE TITLE
Extending Webpack

### ISSUE THREAD

**Issue by anweshknayak** [Cloud-CV/IDE#25]
task runner which runs our various tasks of compiling JS, bundling it and reloading browser on change.

**Comment by tocttou** [comment]
There is webpack already included in the project. Extend it instead.

https://github.com/Cloud-CV/IDE/blob/master/webpack.config.js

**Comment by tocttou** [comment]
As you can see, it already transpiles [1] and bundles JS and other assets also [2]:

1: https://github.com/Cloud-CV/IDE/blob/master/webpack.config.js#L10
2: https://github.com/Cloud-CV/IDE/blob/master/webpack.config.js#L7

To restart the server on file change, you may use: https://webpack.github.io/docs/webpack-dev-server.html

**Comment by anweshknayak** [comment]
thanks @tocttou

**Comment by anweshknayak** [comment]
@tocttou noob question. changes in the files related to frontend are not reflected back. tried running webpack --watch.? Extending this webpack config might help ?

**Comment by tocttou** [comment]
I am not sure why `webpack --watch` does not work for you. It should create new files. Make sure you are refreshing by doing `Ctrl + F5` instead of `F5` to force the browser to fetch actual files instead of the cached ones.

**Comment by virajprabhu** [comment]
@anweshknayak Is this fixed? Like @tocttou said, running with watch + refresh ignoring cache should work fine. Meanwhile I'll add watch to the webpack config.

**Comment by anweshknayak** [comment]
@virajprabhu @tocttou thanks. It is working now :)
