### ISSUE TITLE
Add tensorflow in requirements

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/IDE#26]

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this?

**Comment by deshraj** [comment]
Sure.

**Comment by RishabhJain2018** [comment]
@deshraj Which version should I add?

**Comment by virajprabhu** [comment]
Can you add `0.9.0` for now? 1.0 has been released but we haven't tested with it yet, and it has some breaking changes.

**Comment by RishabhJain2018** [comment]
yeah sure.
