### ISSUE TITLE
Models for Age & Gender Classification Does not work

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/IDE#47]
@virajprabhu @dexter1691 I've used this repo(https://github.com/GilLevi/AgeGenderDeepLearning) for testing the age & gender classification model from their project page (http://www.openu.ac.il/home/hassner/projects/cnn_agegender/) should I try this one?

**Comment by utsavgarg** [comment]
@Ram81 The prototxt files present in that repo are for an older Caffe version, after upgrading those prototxt both models load fine.
![age](https://cloud.githubusercontent.com/assets/11680179/23863636/3f225900-0836-11e7-82c0-6e68c8885ddf.png)

**Comment by Ram81** [comment]
@utsavgarg Thanks for that :+1:
