### ISSUE TITLE
Import without selecting a file should display an error dialog on the UI

### ISSUE THREAD

**Issue by virajprabhu** [Cloud-CV/IDE#5]
Alternatively, we could move the "choose file" functionality into the "import"? Having two steps doesn't seem necessary.

**Comment by anweshknayak** [comment]
any hint ?

**Comment by virajprabhu** [comment]
The import workflow on the UI currently has two steps - you click "choose file" and select a file, and then click "import". We want have only a single button "import" - clicking on it will bring up a file search dialog box and selecting will call import. Is that clearer?

**Comment by virajprabhu** [comment]
@anweshknayak Are you interested in taking this on?

**Comment by anweshknayak** [comment]
@virajprabhu I may need some time to fix this. Semester exams going on. If you can spare me a few days more.

**Comment by virajprabhu** [comment]
@anweshknayak No problem! Let me know if you'd like to work on this once you are free, and I'll assign it to you.

**Comment by anweshknayak** [comment]
@virajprabhu you can assign me this

**Comment by anweshknayak** [comment]
@virajprabhu has this problem already been solved ? we have a import button. clicking it opens up a file search dialog box and selecting it will call import.

**Comment by anweshknayak** [comment]
@virajprabhu please close this
